on:
  push:
    branches:
      - 'main'
    paths: &lua_paths
      - '**.lua'
      - 'extension.xml'
      - '.stylua'
      - '.github/workflows/lua.yml'
  pull_request:
    paths: *lua_paths
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

name: Check Lua Code

jobs:
  stylua:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config-path .stylua.toml --check .

  luacheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - id: name
        uses: mavrosxristoforos/get-xml-info@cc0a00b30a53c3adf0ea2cbfd8314cea394fbbad
        with:
          xml-file: 'extension.xml'
          xpath: |
            root/properties/name

      - id: author
        uses: mavrosxristoforos/get-xml-info@cc0a00b30a53c3adf0ea2cbfd8314cea394fbbad
        with:
          xml-file: 'extension.xml'
          xpath: |
            root/properties/author

      - id: format
        run: |
          # Clean function: strip prefix, remove punctuation/spaces, lowercase
          clean_string() {
            echo "$1" | sed -e 's/^[A-Za-z]\+: *//' -e "s/'//g" -e 's/[^[:alnum:]]//g' | tr '[:upper:]' '[:lower:]'
          }

          echo "name=$(clean_string "${{ steps.name.outputs.info }}")" >> $GITHUB_OUTPUT
          echo "author=$(clean_string "${{ steps.author.outputs.info }}")" >> $GITHUB_OUTPUT

      - uses: leafo/gh-actions-lua@8c9e175e7a3d77e21f809eefbee34a19b858641b
        with:
          luaVersion: 5.1.5

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.config/luacheck
          key: luacheck

      - uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1
        with:
          files: '.'
          config: https://raw.githubusercontent.com/FG-Unofficial-Developers-Guild/Luacheck-Config/main/.luacheckrc
          args: '--no-color --std +${{ steps.format.outputs.name }}${{ steps.format.outputs.author }} --exclude-files .install/*'
          annotate: 'warning'
